- name: Add my user
  ansible.builtin.user:
    name: matteomarchiori
    create_home: true
    group: sudo
    password: $6$Bup0lmjBItHs$Gik6fvCh/n3IMcmvt5iV1Dp4fl4itegO9s48HfIAcYMDsmCrAhQUYyU5tlXcEX2Ws1STn4J/.Qu8lPoNlDLLA0
    update_password: always
    shell: /bin/bash
    state: present

- name: Update repositories cache and install "foo" package
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Install basic packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - net-tools
    - mosh
    - nginx

- name: Install node (last stable version)
  community.general.snap:
    name:
      - node
    classic: yes  

- name: Clone battleship
  ansible.builtin.git:
    repo: https://github.com/ivoputzer/awesome-devops-and-cd-ed4.git
    dest: /home/matteomarchiori/battleship
    version: master

- name: Change file ownership, group and permissions
  command: sudo chown -R vagrant:vagrant battleship
  args:
    chdir: /home/matteomarchiori    

#- name: Install packages based on package.json.
#  community.general.npm:
#    path: /home/matteomarchiori/battleship

- name: Install packages based on package.json.
  command: npm install
  args:
    chdir: /home/matteomarchiori/battleship

- name: Run battleship parcel
  command: npm run dev
  args:
    chdir: /home/matteomarchiori/battleship
  async: 1000
  poll: 0  

- name: Run battleship server.js
  command: npm run start
  args:
    chdir: /home/matteomarchiori/battleship
  async: 1000
  poll: 0 

- name: check status
  shell: ps aux | grep npm
  register: app_status

- debug: msg: {{ app_status.stdout_lines}}

#- name: delete default nginx site
#  file:
#    path: /etc/nginx/sites-enabled/default
#    state: absent
#  notify: restart nginx
#
#- name: copy nginx proxy configuration
#  template:
#    src: battleshipproxy
#    dest: /etc/nginx/sites-enabled/battleshipproxy
#    owner: root
#    group: root
#    mode: '0644'
#  notify: restart nginx